name: Build and Deploy to AWS Lambda

on:
  push:
    branches:
      - main
    tags: 
      - 'v*'
    paths:
      - 'apps/api/**'

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.4'

      - name: Build inside Docker
        run: |
          docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:1.2.4 \
          /bin/bash -c "GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main main.go"
        working-directory: apps/api

      - name: Deploy to AWS Lambda
        env:
          AWS_REGION: 'us-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code --function-name gavinsidhu --zip-file fileb://deployment.zip
        working-directory: apps/api



